#
# Copyright (c) 2019-2022 cnbbx <https://cnbbx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
name: test-build-tools
run-name: Test OpenWrt Build Tools
env:
  REPO_URL: https://github.com/cnbbx/Openwrt-src.git
  REPO_BRANCH: openwrt-22.03
  FEEDS_CONF: feeds.conf.default
  BUILD_USER: ${{ github.actor }}
  TZ: Asia/Shanghai

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container: ghcr.io/cnbbx/openwrt-tools:min
    steps:
    - name: checkout
      uses: actions/checkout@main

    - name: 检查空间使用情况
      run: |
        echo "警告⚠"
        echo -e "-------------- ------------CPU信息------------------------------------------\n"
        echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
        echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
        echo "-------------------------------内存信息-------------------------------------------"
        echo "已安装内存详细信息："
        sudo lshw -short -C memory | grep GiB
        echo -e "\n"
        echo "-----------------------------硬盘信息---------------------------------------------"
        echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
        echo "硬盘详情："
        df -Th

    - name: 克隆软路由源代码
      working-directory: /workdir
      run: |
        git clone --depth=1 $REPO_URL -b $REPO_BRANCH openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt

    - name: 下载自定义项目的清单
      run: |
        [ -e $FEEDS_CONF ] && mv $FEEDS_CONF openwrt/feeds.conf.default
        [ -e youku_yk-l2.config ] && mv youku_yk-l2.config openwrt/.config
        cd openwrt && ls -lh && ./scripts/feeds update -a

    - name: 安装自定义项目的清单
      run: cd openwrt && ./scripts/feeds install -a

    - name: 下载自定义固件插件
      id: package
      if: (!cancelled())
      run: |
        cd openwrt
        make defconfig
        make download -j$(nproc)
        ls -lh
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        make tools/install;
        make toolchain/install;
        ls -lh
